name: PHP Code Review

on:
  push:
    branches:
      - main

jobs:
  php-code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install phpcs
        run: sudo apt-get update && sudo apt-get install -y php-pear && sudo pear install PHP_CodeSniffer

      - name: Run phpcs
        run: phpcs --standard=PSR12 .

      - name: Install Composer dependencies
        run: composer install

      - name: Check PHP Syntax
        run: |
          find . -name "*.php" -print0 | xargs -0 -n1 php -l
