name: PHP Code Review

on:
  push:
    branches:
      - main

jobs:
  php-code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install phpcs
        run: sudo -H pecl install phpcs

      - name: Configure phpcs
        run: phpcs --config-set installed_paths ${{ steps.install_phpcs.outputs.installation_path }}

      - name: Run phpcs
        run: phpcs --standard=PSR12 .
